---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgBNO5CPsGnPOcxkPW1ARH1akWxZFeSJljMT3lG4Mst9Vl6Dut34M89eI3fod70YQj3VTog+UuCQruBHDAZ5S5fXhyHjWws7vGaL10eyPlyq74Gbyf4Kz2oie3utPKdPwVumPBDXUdmo2b8surzDJXja0Anx7GFvfxceB8xJ3kGiwfxDfiIXswAYWBdkNsOPRg/kmnbbXvD2lnbK96/4bN4UuuirM50omAiKqhNJ6iNwfIPth8FeGKg4n3h/anJj0i5hdPV4jeQANLwmthGPgehaq1OSOLpz/5lb37GaMAiTOFEghAzTIXHTeEwsfNNRXIOgHFp5IT2JJWJT7gi6SP52wLBm6q3FrGd68xjIpeJJl67Hd864sLIDHBSINQ7hRuZg5nmN7ztuMGL/7Hunr9Ph869B03b0SndozkkTtq7Ce8edhnVpCHMicOqGrzhlyI3H+tpLkepv69rmY2JGN3euEIPdYlH9CC41mo/f+ILEK6lLJ7gfTB7A4CuWNoWg1pQA7pqQwTaS+kWQdRBtCyEQFrD8kP+UOLvJTUXENInqxXXeFZ2QF6QsORBs3Do0eT4YPQt/oIo/auT9MpaT3JoPQ+SEJgahJ1PlHRY9mif3Q9UyfNMjBhUszbeuwXnj+XGwxCAYfNsBTRN6nAnmPFay3gabiuk1GMwirOFhJCjvlImipqc4+/fcsg/rt84fanpDdEv81hrImjtXwsca3QIIilZ2KQ==
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
    type: Opaque
